### ISSUE TITLE
aarch64 compilation failures - relocation truncated to fit

### ISSUE THREAD

**Issue by tkekan** [intel/isa-l#302] opened 2024-10-31 03:20 UTC
Hello while linking a bazel test that needs an spdk client I'm getting below errors during linking. Please let me know if you need extra information in debugging this further. 

Env:
OL8 docker running on Apple M3 Silicon. 
The same build runs fine on X86_64 docker running on X86 host but this build fails on aarch64. docker on Darwin arm64
```
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x1_ce.o): in function `sha256_mb_ce_x1':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x1_ce.S:115:(.text+0xc): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x2_ce.o): in function `sha256_mb_ce_x2':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x2_ce.S:144:(.text+0x28): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x3_ce.o): in function `sha256_mb_ce_x3':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x3_ce.S:166:(.text+0x34): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x4_ce.o): in function `sha256_mb_ce_x4':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x4_ce.S:195:(.text+0x40): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha512_mb_x1_ce.o): in function `sha512_mb_ce_x1':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha512_mb/aarch64/sha512_mb_x1_ce.S:140:(.text+0xc): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha512_mb_x2_ce.o): in function `sha512_mb_ce_x2':
/root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha512_mb/aarch64/sha512_mb_x2_ce.S:230:(.text+0x28): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
collect2: error: ld returned 1 exit status
```

**Comment by liuqinfei** [comment] 2024-11-07 01:58
> Hello while linking a bazel test that needs an spdk client I'm getting below errors during linking. Please let me know if you need extra information in debugging this further.
> 
> Env: OL8 docker running on Apple M3 Silicon. The same build runs fine on X86_64 docker running on X86 host but this build fails on aarch64. docker on Darwin arm64
> 
> ```
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x1_ce.o): in function `sha256_mb_ce_x1':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x1_ce.S:115:(.text+0xc): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x2_ce.o): in function `sha256_mb_ce_x2':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x2_ce.S:144:(.text+0x28): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x3_ce.o): in function `sha256_mb_ce_x3':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x3_ce.S:166:(.text+0x34): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha256_mb_x4_ce.o): in function `sha256_mb_ce_x4':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha256_mb/aarch64/sha256_mb_x4_ce.S:195:(.text+0x40): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha512_mb_x1_ce.o): in function `sha512_mb_ce_x1':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha512_mb/aarch64/sha512_mb_x1_ce.S:140:(.text+0xc): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk/lib/libisal_crypto.a(sha512_mb_x2_ce.o): in function `sha512_mb_ce_x2':
> /root/.cache/bazel/_bazel_root/78159c4ab73ed818c6000c3e550185d3/sandbox/processwrapper-sandbox/5161/execroot/_main/bazel-out/aarch64-fastbuild/bin/third-party/spdk/spdk.build_tmpdir/isa-l-crypto/sha512_mb/aarch64/sha512_mb_x2_ce.S:230:(.text+0x28): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against `.rol0_data.cst16'
> collect2: error: ld returned 1 exit status
> ```

According to the logs, the problem is releated to isa-l_crypto not isa-l.

**Comment by liuqinfei** [comment] 2024-11-07 02:08
@tkekan If it is with isa-l. Please show the steps for reproducing the issue.

**Comment by tkekan** [comment] 2024-11-12 18:06
Yep it's occuring due to isa-l_crypto,  do you want me to share the steps to repro when linked with libisal_crypto.a ?
> @tkekan If it is with isa-l. Please show the steps for reproducing the issue.

**Comment by pablodelara** [comment] 2024-11-26 17:23
@liuqinfei could you look any further?

**Comment by liuqinfei** [comment] 2024-12-02 06:33
> @liuqinfei I have the steps here: [intel/isa-l_crypto#152](https://github.com/intel/isa-l_crypto/issues/152)

I am not familar with Bazel. What's your platform?

**Comment by liuqinfei** [comment] 2024-12-02 06:48
Oh, i find the [similar issue](https://www.mail-archive.com/u-boot@lists.denx.de/msg382185.html), maybe you can try this.
@tkekan

**Comment by pablodelara** [comment] 2024-12-09 17:23
Anything here? We are looking into releasing 2.31.1 as soon as next week, with just bug fixes, so it would be nice to get this merged. @tkekan @liuqinfei

**Comment by liuqinfei** [comment] 2024-12-10 01:02
> Anything here? We are looking into releasing 2.31.1 as soon as next week, with just bug fixes, so it would be nice to get this merged. @tkekan @liuqinfei

Indeed, this issue is related to isa-l_crypto and should not impact the release of the isal version.

**Comment by pablodelara** [comment] 2024-12-10 08:25
Thanks, should have read this more carefully :) I'll close this issue here.

**Closed by pablodelara** 2024-12-10 08:25 UTC
